//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdK22CNT4Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DcdAccount
    {
        public int DcdID { get; set; }
        public string DcdUserName { get; set; }
        public string DcdPassword { get; set; }
        public string DcdFullName { get; set; }
        public string DcdEmail { get; set; }
        public string DcdPhone { get; set; }
        public Nullable<bool> DcdActive { get; set; }
    }
}
