//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdK22CNT4Lesson11_2210900095.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DcdCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DcdCategory()
        {
            this.DcdProduct = new HashSet<DcdProduct>();
        }
        [Display(Name ="Mã Danh Mục ")]
        public int DcdID { get; set; }
        [Display(Name = "Tên Danh Mục")]
        public string DcdCateName { get; set; }
        [Display(Name = "Trạng Thái")]
        public Nullable<bool> DcdStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DcdProduct> DcdProduct { get; set; }
    }
}
