//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdK22CNT4Lesson11_2210900095.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DcdProduct
    {
        public string DcdId2210900095 { get; set; }
        public string DcdProName { get; set; }
        public Nullable<int> DcdQty { get; set; }
        public Nullable<double> DcdPrice { get; set; }
        public Nullable<int> DcdCateId { get; set; }
        public Nullable<bool> DcdActive { get; set; }
    
        public virtual DcdCategory DcdCategory { get; set; }
    }
}
