//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdLesson09Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcdKetQua
    {
        public string dcdMaSV { get; set; }
        public string dcdMaMH { get; set; }
        public Nullable<decimal> Diem { get; set; }
    
        public virtual dcdMonHoc dcdMonHoc { get; set; }
        public virtual dcdSinhVien dcdSinhVien { get; set; }
    }
}
