//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdLesson09Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcdKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dcdKhoa()
        {
            this.dcdSinhVien = new HashSet<dcdSinhVien>();
        }
    
        public string DcdMaKH { get; set; }
        public string DcdTenKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dcdSinhVien> dcdSinhVien { get; set; }
    }
}
