//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdLesson09Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcdMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dcdMonHoc()
        {
            this.dcdKetQua = new HashSet<dcdKetQua>();
        }
    
        public string DcdMaMH { get; set; }
        public string DcdTenMH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dcdKetQua> dcdKetQua { get; set; }
    }
}
