//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdLesson09Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DcdK22CNT4Lesson09DbEntities4 : DbContext
    {
        public DcdK22CNT4Lesson09DbEntities4()
            : base("name=DcdK22CNT4Lesson09DbEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dcdKhoa> dcdKhoa { get; set; }
        public virtual DbSet<dcdMonHoc> dcdMonHoc { get; set; }
        public virtual DbSet<dcdSinhVien> dcdSinhVien { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
