//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdLesson12_2210900095.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DCD_SACH
    {
        [Display(Name="Mã Sách")]
        public string Dcd_MaSach { get; set; }
        [Display(Name = "Tên Sách")]
        public string Dcd_TenSach { get; set; }
        [Display(Name = "Số Trang")]
        public Nullable<decimal> Dcd_SoTrang { get; set; }
        [Display(Name = "Năm Xuất Bản")]
        public Nullable<System.DateTime> Dcd_NamXB { get; set; }
        [Display(Name = "Mã Tác Giả")]
        public string Dcd_MaTG { get; set; }
        [Display(Name = "Trạng Thái")]
        public Nullable<bool> Dcd_TrangThai { get; set; }
    
        public virtual DCD_TACGIA DCD_TACGIA { get; set; }
    }
}
