//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdLesson12_2210900095.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DinhCongDinh_2210900095Entities2 : DbContext
    {
        public DinhCongDinh_2210900095Entities2()
            : base("name=DinhCongDinh_2210900095Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DCD_SACH> DCD_SACH { get; set; }
        public virtual DbSet<DCD_TACGIA> DCD_TACGIA { get; set; }
    }
}
