//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcdLesson07Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dcdSinhVien
    {
        public string DcdMaSV { get; set; }
        public string DcdHoSV { get; set; }
        public string DcdTenSv { get; set; }
        public Nullable<System.DateTime> DcdNgaySinh { get; set; }
        public Nullable<bool> DcdPhai { get; set; }
        public string DcdPhone { get; set; }
        public string DcdEmail { get; set; }
        public string DcdMaKH { get; set; }
    
        public virtual dcdKhoa dcdKhoa { get; set; }
    }
}
